apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: garimajpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: garimajpipelinesjavascriptdocker 
    spec:
      containers:
        - name: garimajpipelinesjavascriptdocker 
          image: acr145.azurecr.io/garimajpipelinesjavascriptdocker
          ports:
          - containerPort: 8080